version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.0.0

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pytest --cov
      - run:
          name: Black
          command: |
            black -l 100 --check accounts the_only_to_do_list_backend
      - run:
          name: Flake8
          command: |
            flake8 accounts the_only_to_do_list_backend
      - codecov/upload
